version: "3.9"
services:
  backend:
    build: Backend/
    ports:
      - "8000:8000"
    container_name: backend
  frontend:
    build: Frontend/
    ports:
      - "8001:3000"
    container_name: frontend
  dbmysql:
    image: mysql
    ports:
      - "8002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: bind
        source: ./MySql/data/db
        target: /var/lib/mysql
