version: "3.9"
services:
  dbmysql:
    build: MySql/
    ports:
      - "8002:3306"
  dbmongo:
    build: Mongo/
    ports:
      - "8003:27017"
  backend:
    build: Backend/
    ports:
      - "8000:8000"
    container_name: backend
  frontend:
    build: Frontend/
    ports:
      - "8001:3000"
    container_name: frontend

