version: "3.9"
services:
  backend:
    build: Backend/
    ports:
      -"8000:80"
  frontend:
    build: Frontend/
    ports:
      -"8001:80"
  ocr:
    build: OCR/
    ports:
      -"8002:80"
  auth:
    build: Authentication/
    ports:
      -"8002:80"


